### ISSUE TITLE
Perfs

### ISSUE THREAD

**Issue by JohnCoene** [zac-garland/automated.workflow.min#1]
It's good but careful on the minutes on your plan, default R actions come with

```yaml
- name: Cache R packages
  if: runner.os != 'Windows'
  uses: actions/cache@v2
  with:
    path: ${{ env.R_LIBS_USER }}
    key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
    restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
```

Installing packages takes a long time and a lot of money, this helps a ton.
